server:
  port: 6975
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nknowledge?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: yx123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# jwt
jwt:
  secret: ye-xing-secret